[project]
name = "prefect-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prefect>=3.6.4",
    "prefect-aws>=0.7.1",
    "urllib3<2",
]
